### ISSUE TITLE
[BUG]: Adding new user genre will cause the agents to fail

### ISSUE THREAD

**Issue by fourstix** [CodyBerenson/PGMA-Modernized#305]
# Mandatory #

## Describe the bug: ## 
Multiple agents are failing to scrape due to an error in the log 'Could Not Set Agent Parameters QUIT' after upgrading to the latest version. 

I added a new film named (Falcon) - Tahoe Snow Plowed.mp4 and noticed that the agents did not scrape the metadata.  I stopped and restarted the Plex Server, and turned off the VPN client service, but the agents still will not scrape. 

After attempting to scrap, I see this message in the tail of the all agent logs (using GEVI as an example):

2024-06-27 09:15:51,147 (7fb4cee61b38) :  INFO (sandbox:19) - GEVI  -       ----------------------------------------------------------------------------------------------------
2024-06-27 09:15:51,147 (7fb4cee61b38) :  INFO (sandbox:19) - GEVI  - UTILS :: 	Start Scrape Process         ❌ No
2024-06-27 09:15:51,148 (7fb4cee61b38) :  INFO (sandbox:19) - GEVI  - ********************************************************************************************************************************************
2024-06-27 09:15:51,149 (7fb4cee61b38) :  INFO (sandbox:19) - GEVI  - ********************************************************************************************************************************************
2024-06-27 09:15:51,150 (7fb4cee61b38) :  INFO (sandbox:19) - GEVI  - ********************************************************************************************************************************************
2024-06-27 09:15:51,392 (7fb4cee61b38) :  ERROR (utils:5497) - GEVI - SEARCH:: ❌ File: , Line: , Function: _process_function_call -> _search -> search
2024-06-27 09:15:51,392 (7fb4cee61b38) :  ERROR (utils:5498) - GEVI - SEARCH::    Error: Could Not Set Agent Parameters QUIT
2024-06-27 09:15:51,393 (7fb4cee61b38) :  INFO (sandbox:19) - GEVI  - ********************************************************************************************************************************************
2024-06-27 09:15:51,395 (7fb4cee61b38) :  DEBUG (runtime:88) - Sending packed state data (104 bytes)
2024-06-27 09:15:51,396 (7fb4cee61b38) :  DEBUG (runtime:924) - Response: [200] str, 320 bytes
2024-06-27 09:15:51,435 (7fb4cee61b38) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.GEVI/messaging/function/X0FnZW50S2l0OkVyYXNlTWV0YWRhdGE_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMgpzNQpNb3ZpZXMxMAptZWRpYV90eXBlczQ3CmNvbS5wbGV4YXBwLmFnZW50cy5HYXlBZHVsdEZpbG1zOi8vODU5OD9sYW5nPWVuczQKZ3VpZHIwCg__
2024-06-27 09:15:51,438 (7fb4cee61b38) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2024-06-27 09:15:51,440 (7fb4cee61b38) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.GEVI/messaging/function/X0FnZW50S2l0OkVyYXNlTWV0YWRhdGE_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMgpzNQpNb3ZpZXMxMAptZWRpYV90eXBlczQ3CmNvbS5wbGV4YXBwLmFnZW50cy5HYXlBZHVsdEZpbG1zOi8vODU5OD9sYW5nPWVuczQKZ3VpZHIwCg__
2024-06-27 09:15:51,444 (7fb4cee61b38) :  DEBUG (runtime:88) - Sending packed state data (104 bytes)
2024-06-27 09:15:51,444 (7fb4cee61b38) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes

These agents were all working previously before the update to the latest version.

## Specific Agent(s) Causing the Issue: ##
GEVI, AEBN, GayEmpire, GayHotMovies (basically all the agents I use *except* the NFOImporter agent.)

## Index Site URL(s) Attempting to Match: ##
https://gayeroticvideoindex.com/video/47804

## Log Attached: ##

GayAdultFilm.log  
[com.plexapp.agents.GayAdultFilms.log](https://github.com/user-attachments/files/16014747/com.plexapp.agents.GayAdultFilms.log)

GEVI.log
[com.plexapp.agents.GEVI.log](https://github.com/user-attachments/files/16014748/com.plexapp.agents.GEVI.log)

AEBN.log
[com.plexapp.agents.AEBN.log](https://github.com/user-attachments/files/16014749/com.plexapp.agents.AEBN.log)

GayEmpire.log
[com.plexapp.agents.GayEmpire.log](https://github.com/user-attachments/files/16014752/com.plexapp.agents.GayEmpire.log)

GayHotMovies.log
[com.plexapp.agents.GayHotMovies.log](https://github.com/user-attachments/files/16014755/com.plexapp.agents.GayHotMovies.log)

system.log
[com.plexapp.system.log](https://github.com/user-attachments/files/16014768/com.plexapp.system.log)

# Optional #

## Screenshot(s) with all nudity redacted: ##
![Screenshot 2024-06-27 092300](https://github.com/CodyBerenson/PGMA-Modernized/assets/5274281/9d17c7c4-51ac-4569-a161-278cf79210b9)

## Desktop (please complete the following information): ##
    OS: [e.g. iOS] Qnap QTS 5.1.7.2770 (based on Linux Ubuntu)
    Browser [e.g. chrome, safari] Firefox 127.01 64-bit
    Version [e.g. 22]: Plex Media Server 1.40.3

**Comment by JPH71** [comment]
Go to settings...agents.. gay films... and cluck the gear icon and save the
settings for each agent... then restart plex... it looks like you gave lost
your agent preferences..

The json files were not touch, that deal with the preferences, so I do not
understand why this is happening to you..

**Comment by fourstix** [comment]
Just did that for the "Gay Adult", "Gay Adult Scenes" and "Gay Adult Films" agents, then stopped and restarted the Plex server.  I still get the same errors in the logs.

**Comment by JPH71** [comment]
Ok, I will look through the logs and get back to you.

**Comment by fourstix** [comment]
In case you need it to help debugging, I pretty much have all the options set off for the agents, and Use Background Art is the only box I have checked, plus I have the xml token set.

Here is a screen shot for the GEVI agent, all the agents are configured like this:

![GEVI Settings 1](https://github.com/CodyBerenson/PGMA-Modernized/assets/5274281/e7416e6d-8262-4ce6-912c-7bf8198ab770)
![GEVI Settings 2](https://github.com/CodyBerenson/PGMA-Modernized/assets/5274281/6cb1f2da-4572-4567-ac30-e1a1c3e1b170)

**Comment by JPH71** [comment]
cheers - for this - looking at it now
as i have a friend popping over for drinks to celebrate the end of his
exams later!

**Comment by JPH71** [comment]
Could you try this, and then let me:
https://drive.google.com/file/d/1qI3hmzzIlkDVF5jlqwTx6vES8eG8bSvF/view?usp=sharing

put it in the code folder for each agent... then let me know.

Another thing: make sure all your genre tidy files do not have an empty
line even at the end.

Cheers and thanks for finding this!

Cheers

Jason

**Comment by fourstix** [comment]
Hi Jason,
I made sure that UserGenres.txt and UserGayTidy.txt did not have any blank lines in them and I copied the utils.py file into the agent directories, then stopped and restarted Plex, but I still get the same error.

**Comment by fourstix** [comment]
You got me thinking, which is always dangerous.  I went in and renamed my UserGayTidy.txt and my UserGenres.txt files to add xxx before their names so they would not be processed.   I also unchecked all but the GEVI agent to simplify things.  This allowed the GEVI to run and scrape the movie.    

My User files are from the old release, I didn't update them so they probably don't match the new ones.

**Comment by fourstix** [comment]
Renaming xxUserGenres.txt back to UserGenres.txt and rerunning the Refresh Metadata option works.  The GEVI agent scrapped successfully.  However renaming xxxUserTidy.txt back to UserTidy.txt causes it to fail again.  

Here's the offending UserTidy.txt file that causes the Agents to fail:
[UserGayTidy.txt](https://github.com/user-attachments/files/16020246/UserGayTidy.txt)

I ran a file compare and they are very different, with unique lines in both files.  So I'm going to try editing the new GayTidy.txt file to create a new UserTidy.txt that has the same lines but with different Genres and see if that works.

**Comment by fourstix** [comment]
In case you need it, here is the UserGenres.txt file that I am using.
[UserGenres.txt](https://github.com/user-attachments/files/16020301/UserGenres.txt)

**Comment by fourstix** [comment]
I updated the UserGayTidy.txt file, but it still fails.  I wonder if it's due to the fact that it's not picking up the UserGenre.txt genres that I added.  For example, I see an error message following each instance of the "Pre-Condom" genre like this:

2024-06-27 17:50:39,778 (7fbd50a82b38) :  INFO (sandbox:19) - GEVI  - UTILS :: 		UserGayTidy.txt: Duplicate Row - Replace Setting Row 1755 - Vintage / Classic Porn::Pre-Condom
2024-06-27 17:50:39,779 (7fbd50a82b38) :  INFO (sandbox:19) - GEVI  - UTILS :: 		UserGayTidy.txt: Not Found in GayGenres.txt Row 1755 - Vintage / Classic Porn::Pre-Condom

**Comment by JPH71** [comment]
I will look at this in the morning...
If you create a brand new genre, you also have to create an icon for it...

Is it passing the previous error?

**Comment by fourstix** [comment]
The new genres all had icon files in the black directory, and it was failing at exactly the same place.  I copied the new icon files into *all* of the color directories under the Genre directory, and now the GEVI agent appears to be working.  

It used to work when /Genre/black was the only directory with the new genre icons. Now I guess it's required to add them to all colors to define the genres, even though have the genre collection set to "No" rather than a color.

**Comment by JPH71** [comment]
That is correct...
Genres have to have an icon

**Comment by fourstix** [comment]
I've done some more playing around.

Here are the UserGenres.txt and UserGayTidy.txt file that I would like to have work on my Plex server for the agents.  If I rename these files as GayGenres.txt and GayTidy.txt in the _PGMA directory, then the Agent will work with the new Genres.

[UserGayTidy.txt](https://github.com/user-attachments/files/16030121/UserGayTidy.txt)
[UserGenres.txt](https://github.com/user-attachments/files/16030122/UserGenres.txt)

Since the agent works with these Genre and Tidy files as base files, with no errors in the log, that indicates to me that the file contents are consistent, with no internal errors.  I think they should be processed as valid UserGenres.txt and UserGayTidy.txt files.

However if I try to add or update the original Genres with these files as user files, named as UserGenres.txt and UserGayTidy.txt and using the original base GayGenres.txt and GayTidy.txt files, then the entries in UserGayTidy.txt that map to a new Genre fail with the following message.

2024-06-28 09:08:27,990 (7fbd50a82b38) :  INFO (sandbox:19) - GEVI  - UTILS :: 7.	Prepare Tidied Dictionary of Genres and Countries
2024-06-28 09:08:27,991 (7fbd50a82b38) :  INFO (sandbox:19) - GEVI  - UTILS :: 	Tidy Files                   ['GayTidy.txt', 'UserGayTidy.txt']
2024-06-28 09:08:27,993 (7fbd50a82b38) :  INFO (sandbox:19) - GEVI  - UTILS :: 		UserGayTidy.txt: Not Found in GayGenres.txt Row 29 - 3 Some::Group Sex
2024-06-28 09:08:27,993 (7fbd50a82b38) :  INFO (sandbox:19) - GEVI  - UTILS :: 		UserGayTidy.txt: Not Found in GayGenres.txt Row 30 - 3 Some (Boy/Boy/Girl)::Group Sex
2024-06-28 09:08:27,994 (7fbd50a82b38) :  INFO (sandbox:19) - GEVI  - UTILS :: 		UserGayTidy.txt: Not Found in GayGenres.txt Row 32 - 3-Way::Group Sex
2024-06-28 09:08:27,995 (7fbd50a82b38) :  INFO (sandbox:19) - GEVI  - UTILS :: 		UserGayTidy.txt: Not Found in GayGenres.txt Row 34 - 40+::Bears
2024-06-28 09:08:27,995 (7fbd50a82b38) :  INFO (sandbox:19) - GEVI  - UTILS :: 		UserGayTidy.txt: Not Found in GayGenres.txt Row 38 - 50+::Bears
2024-06-28 09:08:27,996 (7fbd50a82b38) :  INFO (sandbox:19) - GEVI  - UTILS :: 		UserGayTidy.txt: Not Found in GayGenres.txt Row 39 - 70's::Pre-Condom
<Several more error lines omitted>

It looks like the Genre dictionary did not get the UserGenres added to it, so all the lines in the UserGayTidy that point to new genres are giving an error.

**Comment by fourstix** [comment]
One more thing.  If I manually merge the User Genres into the GayGenres file, then the GayTidy.txt and UserGayTidy.txt files processed without errors and Agent runs correctly.  But if I have the original GayGenres.txt file and the UserGenres.txt files separate, the Agent fails to scrape with the errors noted above.

**Comment by fourstix** [comment]
I can get it down to a simple case where adding single new user genre will cause the agents to fail.  

Here are the UserGenre.txt and UserGayTidy.txt files and icon file that define a single new Genre "Socks" which is currently not mapped, along with the GEVI agent log file showing that the new Genre caused the agent to fail.

[SimpleUserGenres.txt](https://github.com/user-attachments/files/16041945/SimpleUserGenres.txt)
[SimpleUserGayTidy.txt](https://github.com/user-attachments/files/16041946/SimpleUserGayTidy.txt)
<img width="110" alt="Socks" src="https://github.com/CodyBerenson/PGMA-Modernized/assets/5274281/ac5a42e4-001d-486f-9f18-7b952a46e603">
[com.plexapp.agents.GEVI.log](https://github.com/user-attachments/files/16041948/com.plexapp.agents.GEVI.log)

**Comment by JPH71** [comment]
Please look at the discussion I have raised....
My suggestion in regards to Genres vs Categories will simplify this 
I will look intot UserGenres files and get back to you....

**Comment by fourstix** [comment]
Thanks, I responded to the discussion.  Personally, I prefer Genres to be in Categories rather than in Collections.  

I like to have my own set of Genres, and I'm fine with using the mapping scheme defined in UserGenres.txt and UserGayTidy.txt.  That scheme just stopped working for me in the last release.

**Comment by JPH71** [comment]
I am also coming to the conclusion that genres as categories better... And we keep collections for Actors, Directors  and actual collections (Series of Films)

**Comment by JPH71** [comment]
Net code loaded to the repository should fix this - in the attached files this was how I set up the Socks genre. And you have the png file in the icon folder...

[UserGayTidy.txt](https://github.com/user-attachments/files/16575808/UserGayTidy.txt)
[UserGayGenres.txt](https://github.com/user-attachments/files/16575809/UserGayGenres.txt)

**Comment by fourstix** [comment]
Hi, I still cannot add new Genres.  Here is the UserGayGenre.txt file I"m trying to load.

I removed all the duplicates in this file with GayGenre.txt because they were giving errors, but still I get this error message in the logs.

2024-08-12 12:30:30,319 (7f7741cceb38) :  INFO (sandbox:19) - GEVI  -       ----------------------------------------------------------------------------------------------------
2024-08-12 12:30:30,319 (7f7741cceb38) :  INFO (sandbox:19) - GEVI  - UTILS :: 6.	Prepare Dictionary of Genres and Symbols
2024-08-12 12:30:30,320 (7f7741cceb38) :  INFO (sandbox:19) - GEVI  - UTILS :: 		Tidy Files                  ['GayGenres.txt', 'UserGayGenres.txt']
2024-08-12 12:30:30,351 (7f7741cceb38) :  ERROR (utils:5484) - GEVI - UTILS :: ❌ File: utils.py, Line: 7714, Function: _search -> search -> setupAgentVariables
2024-08-12 12:30:30,351 (7f7741cceb38) :  ERROR (utils:5485) - GEVI - UTILS ::    Error: creating Genres Dictionary: string index out of range
2024-08-12 12:30:30,380 (7f7741cceb38) :  ERROR (utils:5484) - GEVI - UTILS :: ❌ File: utils.py, Line: 7714, Function: _search -> search -> setupAgentVariables
2024-08-12 12:30:30,380 (7f7741cceb38) :  ERROR (utils:5485) - GEVI - UTILS ::    Error:: Genres Source File: /share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Library/Plex Media Server/Plug-ins/_PGMA/UserGayGenres.txt
2024-08-12 12:30:30,381 (7f7741cceb38) :  INFO (sandbox:19) - GEVI  -       ----------------------------------------------------------------------------------------------------
2024-08-12 12:30:30,382 (7f7741cceb38) :  INFO (sandbox:19) - GEVI  - UTILS :: 	Start Scrape Process         ❌ No
2024-08-12 12:30:30,382 (7f7741cceb38) :  INFO (sandbox:19) - GEVI  - ********************************************************************************************************************************************
2024-08-12 12:30:30,383 (7f7741cceb38) :  INFO (sandbox:19) - GEVI  - ********************************************************************************************************************************************
2024-08-12 12:30:30,383 (7f7741cceb38) :  INFO (sandbox:19) - GEVI  - ********************************************************************************************************************************************
2024-08-12 12:30:30,405 (7f7741cceb38) :  ERROR (utils:5484) - GEVI - SEARCH:: ❌ File: , Line: , Function: _process_function_call -> _search -> search
2024-08-12 12:30:30,406 (7f7741cceb38) :  ERROR (utils:5485) - GEVI - SEARCH::    Error: Could Not Set Agent Parameters QUIT
2024-08-12 12:30:30,406 (7f7741cceb38) :  INFO (sandbox:19) - GEVI  - ********************************************************************************************************************************************
   
[UserGayGenres.txt](https://github.com/user-attachments/files/16589697/UserGayGenres.txt)

Am I doing something wrong?

**Comment by fourstix** [comment]
I think the issue might be with my UserGayTidy.txt file.  I'm still trying to isolate the problem.

**Comment by fourstix** [comment]
I figured it out.  It's end of file character Windows adds at the end of the file, which becomes a blank line in Linux.  I had to use a hex editor to snip it out the last empty line from UserGayGenres.txt and UserGayTidy.txt.  Once I did that they began to work as expected.

**Comment by JPH71** [comment]
Also your middle eastern value has no .png at the end...

**Comment by fourstix** [comment]
Good catch, Thanks.  I added the .png to the Middle Eastern entry in UserGayGenres.txt.  

I believe the problem was the end of file character that Windows editors add to text files that caused the problem.

**Comment by JPH71** [comment]
Thanks for letting me know about that...
I will let Cody now so that he can highlight it..

If it's working close the issue xxxx

**Comment by fourstix** [comment]
Yes.  I agree that this issue is now fixed, and I'll close it.  Many thanks for fixing it so quickly!
